# Generated by Django 3.2.10 on 2021-12-11 14:02

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('image', models.ImageField(storage=djongo.storage.GridFSStorage(base_url='http://127.0.0.1:8000/images_Data/', collection='images_Data'), upload_to='')),
                ('image_encoding', models.BinaryField()),
            ],
        ),
    ]
